
        (function(props) {
            window.Core.utils.renderBootstrap({
                elId: 'bs-18',
                componentName: 'CookieBanner',
                props: props,
                contextKey: 'context-bs-18'
            });
        }
        )({
            "bannerTitle": "Cookie Policy",
            "buttonText": "Accept",
            "message": "{\"blocks\":[{\"key\":\"688aj\",\"text\":\"This website uses cookies. By continuing to view this site, you accept our use of cookies.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
            "className": "widget-footer-footer-3",
            "children": null,
            "_category": "layout24_accent",
            "copyright": "{\"blocks\":[{\"key\":\"3vgg4\",\"text\":\"Copyright © 2017 - 2019 cheesits456#6494\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
            "poweredBy": "Powered by Google Domains and Github Pages",
            "preset": "footer3",
            "schemaVersion": "1",
            "socialAccountsEnabled": true,
            "pages": [{
                "isFlyoutMenu": false,
                "active": false,
                "pageId": "2dd73f31-d076-4b79-8aa3-b8f1627ef644",
                "name": "Add Bot",
                "href": "http:\u002F\u002Finvite.haileybot.com",
                "target": "_blank",
                "visible": true,
                "requiresAuth": false,
                "rel": "noopener",
                "type": "page",
                "showInFooter": true
            }, {
                "isFlyoutMenu": false,
                "active": false,
                "pageId": "de363f11-e5df-4a5a-9266-d6454c646a8d",
                "name": "Join Support Server",
                "href": "http:\u002F\u002Fdiscord.gg\u002F7QH4YeD",
                "target": "_blank",
                "visible": true,
                "requiresAuth": false,
                "rel": "noopener",
                "type": "page",
                "showInFooter": true
            }, {
                "isFlyoutMenu": false,
                "active": false,
                "pageId": "ea4e260e-843b-40fd-9217-cda35ac068b6",
                "name": "Overview",
                "href": "http:\u002F\u002Fdocs.haileybot.com",
                "target": "_blank",
                "visible": true,
                "requiresAuth": false,
                "rel": "noopener",
                "type": "page",
                "showInFooter": true
            }, {
                "isFlyoutMenu": false,
                "active": false,
                "pageId": "3459494c-ba3a-47e9-b0e7-8741f1c6cb16",
                "name": "FAQ",
                "href": "http:\u002F\u002Fdocs.haileybot.com\u002Ffaq",
                "target": "_blank",
                "visible": true,
                "requiresAuth": false,
                "rel": "noopener",
                "type": "page",
                "showInFooter": true
            }, {
                "isFlyoutMenu": false,
                "active": false,
                "pageId": "89080aad-8bbd-474d-bfed-343b6b42f681",
                "name": "ChangeLog",
                "href": "http:\u002F\u002Fdocs.haileybot.com\u002Fv\u002Fchangelog\u002F",
                "target": "_blank",
                "visible": true,
                "requiresAuth": false,
                "rel": "noopener",
                "type": "page",
                "showInFooter": true
            }],
            "socialProfiles": {
                "socialAccountsEnabled": true,
                "facebookProfile": "229354854684653",
                "twitterProfile": "haileybot_",
                "instagramProfile": "hailey.bot",
                "pinterestProfile": null,
                "linkedinProfile": null,
                "youtubeProfile": "channel\u002FUCbmXX7raBEUkZqs-5gX0mSA",
                "googlePlusProfile": null,
                "yelpProfile": null,
                "xingProfile": null
            },
            "facebookProfile": "229354854684653",
            "twitterProfile": "haileybot_",
            "instagramProfile": "hailey.bot",
            "pinterestProfile": null,
            "linkedinProfile": null,
            "youtubeProfile": "channel\u002FUCbmXX7raBEUkZqs-5gX0mSA",
            "googlePlusProfile": null,
            "yelpProfile": null,
            "xingProfile": null,
            "featureFlags": {
                "showAutoBillText": false,
                "newAccountOrionBypass": false,
                "redirectSSOols_lp": false,
                "commercePlanDisabled": false,
                "redesignedUpgradeModal": false,
                "enableAcquiredAccountView": false,
                "enableFBPageSuggestions": false,
                "enableYelpFlow": true,
                "showPopularVerticals": true,
                "enableDnsv2": true,
                "allowInAppUpgradeSEOFT": true,
                "enableSkipOnespace": false,
                "enableMoveSections": true,
                "enableGmbFlowToBusiness": false,
                "moveButtonPlacement": true,
                "enableNewAddSectionMobile": false,
                "enableNewPlanSwitchingModalDesign": false,
                "showCoupon": false,
                "mapRenderProvider": "mapbox",
                "enableMalwareScanning": true,
                "enableO365XSell": false,
                "enableOnespaceSandbox": false,
                "enableFbGxIntegration": false,
                "couponToggleHidden": false,
                "stockPhotoSearch": true,
                "enableFbMetrics": true,
                "geosuggestProvider": "mapbox",
                "showFreeTrialBannerBottom": true,
                "disablePIIMarket": false,
                "enablePreviewBrowserChromeHttp": true,
                "debugOlaPaypalAuthorize": false,
                "discountCodes": false,
                "enableSslForExtDomain": true,
                "enableBlog": true,
                "enableGMB4All": false,
                "checkout": {
                    "enableMoneyBackGuaranteeText": false
                },
                "enableFBPreviewExperiment": false,
                "enableGMBPostProductCard": false,
                "enableFBTimingExperiment": false,
                "enableGmbFlow": true,
                "GMBExperimentalUx": false,
                "receiptPage": {
                    "coaching": {
                        "disabled": false
                    },
                    "difyPhotoshoot": {
                        "disabled": true
                    },
                    "socialMediaManager": {
                        "difySocial": {
                            "disabled": false
                        }
                    }
                },
                "enablePlansCC": true,
                "enableFbConnectV2": true,
                "gridDesignPlansModal": true,
                "strawberryJam": false,
                "enableElderberryJam": true,
                "enablePlans": true,
                "displayVat": false,
                "maxWidowChars": 11,
                "enableMetricsUINonOlsOla": false,
                "enablePlansNoCC": true,
                "disablePII": false,
                "enableFeedback": true,
                "enableOlsProductSorting": "false",
                "hideThemeAndLayoutPivot": true,
                "showEnterpriseNationModal": false,
                "enableFbUpdate": true,
                "enableFBHoursEditFlow": false,
                "enableHTMLHelpLink": true,
                "themeGallery": true,
                "enableHeaderCartIcon": true,
                "allowInAppUpgradeOLAFT": true,
                "enableSeoCallToAction": true,
                "publishUploadInline": false,
                "showPriceDifference": true,
                "enableMapboxMap": false,
                "useWsbvnext": false,
                "termsModalForNonO365Markets": true,
                "manageMemebersTooltip": true,
                "enableV1StatsForFBPublished": false,
                "enableQuickStartPivot": true,
                "enableO365OnPostPublish": false,
                "enableMapboxCorrectionLink": true,
                "enableMktgAsstEntity": true,
                "enableNewFBMetrics": true,
                "enableHeaderTreatments": true,
                "enableFbConnect": true,
                "enableOneSpaceQueuing": false,
                "publishUseChildProcess": true,
                "enableNextSuggestionButton": false,
                "isOLAContactsOn": false,
                "enableMetricsUIFBGMB": true,
                "useHeaderImages": false,
                "enableAddressLine2": true,
                "enableDashboardGXSuggestions": false,
                "enableXing": false,
                "enableGuidanceInEditor": false,
                "showAnnualPrice": false,
                "allowInAppUpgradeOLS": true,
                "olsEditModeCTA": true,
                "domainPaywall": true,
                "memoizeO365EligibilityCall": false,
                "enableNPS": true,
                "enableFBLandingTextVariation": false,
                "enableUpgradeToBusinessPlus": false,
                "enableStatsButton": true,
                "showPIIDisclaimer": false,
                "enableGmbFlowForGCM": true,
                "publish": {
                    "enableDnsNotReadyModal": true,
                    "enableEditorGXSuggestions": false,
                    "enableGoToDashboardButtonForPaidAccounts": true,
                    "enableSocialMetaTags": true,
                    "enableSocialShare": true
                },
                "accountsService": {
                    "launchIntegration": true,
                    "getAccountEvent": true,
                    "updateAccount": true,
                    "subscriptionPassThru": false,
                    "paymentMethods": true,
                    "createAccount": true,
                    "planOptions": false,
                    "trialOfferings": true,
                    "createAccountDirect": true
                },
                "vnextRenderPublish": false,
                "enableExpiredAccountView": false,
                "enableSmartLineXSell": false,
                "redirectSSOwsb_lp": false,
                "enablePostProductSuggestion": false,
                "enableNewSocialAPI": true,
                "olsHideProductsPerPage": false,
                "enableDashboardMaxCards": false,
                "enableSocialAccountsFooter": true,
                "enableSocialPostArticleWizard": true,
                "enableFBViewInsightsButton": true,
                "isSplitEnabled": false,
                "enableDisplayAds": false,
                "enableCommerceSuggestions": false,
                "redirectSSOvt": false,
                "enableAddonGroups": true,
                "enableGMBConnect": true,
                "enableDmStatsForFBMetrics": true,
                "businessProPlanDisabled": true,
                "planAutoUpgradeOLS": true,
                "redirectDppToActivator": true,
                "enableSocialFacebookCreate": true,
                "redirectOnboardingToDcc": false,
                "dmStatsV2": true,
                "verticalPickerESSuggest": true,
                "enableGoogleAddressInput": true,
                "enableDashboardOLA": true,
                "enableIsManual": true,
                "showMaybeLaterButton": false,
                "enableHTMLFeedback": true,
                "commercePayPalPlanDisabled": true,
                "enableSocialAccountsHamburger": true,
                "enableFBReviewReply": true,
                "enableCookieBanner": true,
                "enableFbAddtlFields": true,
                "enableMetricsUI": false,
                "enableMixpanelLogging": true,
                "sendReferralAppeal": false,
                "showDomainPrivacyUpsell": true,
                "shouldRunSplitTest": false,
                "allowInAppUpgradeSEO": true,
                "enableYelpUnchained": false,
                "showGMBSuggestionsPanel": true,
                "enableCountryHelp": false,
                "dashboard": {
                    "rollout": {
                        "gxExperiments": "base"
                    }
                },
                "enableFBHoursPanel": false,
                "useNewZeroStateOLA": false,
                "fullCartCheckout": false,
                "showEmailActivation": true,
                "smallThemePreviewFont": false,
                "enableGMBInternational": true,
                "defaultMonthlyPlan": false,
                "enableCookieWarning": false,
                "enableLightTheme": false,
                "searchEngineSubmission": {
                    "bing": true,
                    "facebook": true,
                    "google": true
                },
                "enableHTMLCenterContent": true,
                "enableGMBHours": true,
                "businessUltimatePlanDisabled": true,
                "enableGMBDuplicateHandling": true,
                "backgroundPosition": "center",
                "waffleMenuLinks": true,
                "enableCombinedDashboardCards": false,
                "isGEMContactsOn": false,
                "enableDuplicatePage": true,
                "enableBuyDomainFromPreview": false,
                "enableCheckCertMismatch": true,
                "enableQuickAdd": true,
                "enableLogEnhancedErrorStack": false,
                "enableFacebookFlow": true,
                "enableWebsiteReset": true,
                "O365XSellForMonthlyTerm": false,
                "enableYelpConnect": false,
                "showPlansModalTitle": false,
                "piq": {
                    "startDate": "2029-02-12T00:00:00.000Z"
                },
                "continueExistingTrialOffer": {
                    "pathways": ["hp", "wsb_lp", "vt", "ols_lp", "pro", "dcc", "mya"]
                },
                "enableMembership": false,
                "enableFBHoursUpdate": false,
                "enableFbCategorySelect": true,
                "planAutoUpgradeSEO": true,
                "useV2SevApi": true,
                "isUSA": true,
                "showO365EmailUpdateOption": true,
                "enableSocialAccountsWidget": true,
                "enableSEVDomainValidationV2": true,
                "enableHeaderThemes": true,
                "enableThemesEditor": true,
                "enableGXLayoutAPICall": true,
                "enableSharedNav": true,
                "enableDashboardOptimizely": false,
                "enableMixpanelUserProfileReporting": true,
                "redirectSSOhp": false,
                "enableSocialPostWizard": true,
                "enableOlsSearch": true,
                "allowInAppUpgradeOLSFT": true,
                "showPIQ": false,
                "onboarding": {
                    "loadPlanTypeFromOrion": false
                },
                "useSkittleColorPalette": true,
                "enableGmbTransferringOwnership": true,
                "enableOneSpaceSubmit": true,
                "enableOlsImageZoom": true,
                "allowInAppUpgradeOLA": true,
                "enableThemesEditorMobile": true,
                "enableEarlyCCLoading": true,
                "enableWidgetSearchBox": true,
                "enableO365Activation": false,
                "showSEVSuggestionsPanel": true,
                "enableCheckCertExpiry": true,
                "howToBubbles": false,
                "enablePinterestMeta": true,
                "enableSearchEngineIndexing": true,
                "enableMembershipRequests": false,
                "lh4u": false,
                "enableMetricsUIAllPlans": true,
                "enableMetricsDisconnectedStates": false,
                "enableColorCategoryChooser": true,
                "enableFacebookPixel": true,
                "hideLegacyThemeSelector": false,
                "enableSeasonalBanner": true,
                "dnsUpdatingModal": true,
                "enableTLAOnespaceSubmit": false,
                "submitSitemapToClassifyAPI": true,
                "urgentBannerThreshold": false,
                "enableGXLayout": true,
                "isOLSContactsOn": false,
                "inlineEditing": true,
                "isOlaPaymentUIOn": true,
                "showSubscribePopup": false,
                "subscriptionExpirationThreshold": 48
            },
            "isAccountFree": null,
            "appName": "Website Builder",
            "cookieBannerEnabled": true,
            "cookieBannerMessage": "{\"blocks\":[{\"key\":\"688aj\",\"text\":\"This website uses cookies. By continuing to view this site, you accept our use of cookies.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
            "cookieBannerTitle": "Cookie Policy",
            "cookieBannerButtonLabel": "Accept",
            "isReseller": null,
            "market": "en-CA",
            "rootDomain": "godaddy.com",
            "planUpgradeLink": "https:\u002F\u002Fwww.godaddy.com\u002Fwebsites\u002Fwebsite-builder?isc=ISC#pricing",
            "pageId": "00000000-0000-0000-0000-000000000000",
            "createDate": "2019-02-09T06:46:50.862Z",
            "value": null,
            "websiteId": "1f943feb-da2d-4d32-b758-f413aef63c46",
            "updateDate": "2019-02-09T14:29:39.361Z",
            "clientResources": ["@wsb\u002Fguac-widget-core\u002Flib\u002Fclient-resource"],
            "type": "FOOTER",
            "staticContent": {
                "usingCookieTitle": "This website is using cookies.",
                "usingCookieMessage": "We use them to give you the best experience. If you continue using our website, we'll assume that you are happy to receive all cookies on this website.",
                "acceptAndClose": "Accept & Close",
                "cookiePolicy": "Cookie Policy",
                "Facebook": "Facebook Social Link",
                "Twitter": "Twitter Social Link",
                "Instagram": "Instagram Social Link",
                "Pinterest": "Pinterest Social Link",
                "LinkedIn": "LinkedIn Social Link",
                "YouTube": "YouTube Social Link",
                "Google+": "Google Plus Social Link",
                "Yelp": "Yelp Social Link",
                "Xing": "Xing Social Link"
            },
            "id": "banner-54a735bf-cd6b-47d4-9098-1219b40306c7",
            "widgetId": "54a735bf-cd6b-47d4-9098-1219b40306c7",
            "section": "default",
            "category": "accent",
            "locale": "en-CA",
            "renderMode": "PUBLISH"
        });